### ISSUE TITLE
SO....HOW DO I INSTALL THIS THESE UTILITIES?

### ISSUE THREAD

**Issue by Peter-Schorn** [sveinbjornt/osxiconutils#6]
I'm new to programming and it's annoying that these basic instructions aren't listed anywhere that I could find in this project. After I downloaded the files, I'm not sure what to do with them . Don't I have to move them to a specific folder or something?

**Comment by joevt** [comment]
Do one of the following:

- Use the full path of the command (so you don't need to install it anywhere)
- Move the commands to one of the folders listed in /etc/paths
- Add the path of a folder containing the commands to /etc/paths
- Create a script that sets up an alias for each command, then when you want to use one of the commands, use the source command to load the script that sets up the aliases, then use the aliases.

**Comment by sveinbjornt** [comment]
These are standard command line utilities. I no longer have the time nor the inclination to maintain or further develop them. Enjoy.
