### ISSUE TITLE
Linux support?

### ISSUE THREAD

**Issue by drone1** [sveinbjornt/osxiconutils#7]
Thank you so much for this awesome work.

I am generating folders on Linux AWS workers and would absolutely love to support folder images for macOS users, but it appears this will only be possible if the workers are running macOS, rather than Linux.

Do you have some idea if it would be possible to build something like this on Linux and if so, what the work would look like?

I see your project is all in Objective C or Swift maybe? I'm assuming the image data is just written as metadata in the folder's 'stat' data, but may be read/written via proprietary Apple code? Or can you give me an overview of how it works/how I might implement it on Linux?

Thank you again!

**Comment by sveinbjornt** [comment]
The functions to read the icon data are only available on macOS, unfortunately, so I don't think running on Linux is an option.

**Comment by drone1** [comment]
Thanks for the quick response, but I think it's possible actually! Check
this out:

https://delightlylinux.wordpress.com/2018/06/12/set-custom-folder-icon-using-bash/
